/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EWasteRegistry } from './EWasteRegistry.js';
export type { IRewardVault } from './IRewardVault.js';