/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EWasteFi {
      
    export type SubmissionStruct = {id: BigNumberish, user: AddressLike, category: string, quantity: BigNumberish, weight: BigNumberish, reward: BigNumberish, status: BigNumberish, submittedAt: BigNumberish, verifiedAt: BigNumberish, rewardCredited: boolean}

    export type SubmissionStructOutput = [id: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint, status: bigint, submittedAt: bigint, verifiedAt: bigint, rewardCredited: boolean] & {id: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint, status: bigint, submittedAt: bigint, verifiedAt: bigint, rewardCredited: boolean }
  
    }

  export interface EWasteFiInterface extends Interface {
    getFunction(nameOrSignature: "addRecycler" | "getRewardBalance" | "getSubmission" | "getSubmissionCount" | "getUserSubmissionIds" | "issueReward" | "owner" | "recyclers" | "rejectSubmission" | "removeRecycler" | "rewardBalances" | "submissionCounter" | "submissions" | "submitEwaste" | "verifySubmission"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EWasteSubmitted" | "RecyclerAdded" | "RecyclerRemoved" | "RewardIssued" | "SubmissionRejected" | "SubmissionVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'addRecycler', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRewardBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSubmission', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSubmissionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserSubmissionIds', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'issueReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'recyclers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rejectSubmission', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeRecycler', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rewardBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'submissionCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'submissions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitEwaste', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifySubmission', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addRecycler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSubmissionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserSubmissionIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recyclers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeRecycler', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissionCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submissions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitEwaste', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifySubmission', data: BytesLike): Result;
  }

  
    export namespace EWasteSubmittedEvent {
      export type InputTuple = [submissionId: BigNumberish, user: AddressLike, category: string, quantity: BigNumberish, weight: BigNumberish, reward: BigNumberish];
      export type OutputTuple = [submissionId: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint];
      export interface OutputObject {submissionId: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecyclerAddedEvent {
      export type InputTuple = [recycler: AddressLike];
      export type OutputTuple = [recycler: string];
      export interface OutputObject {recycler: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecyclerRemovedEvent {
      export type InputTuple = [recycler: AddressLike];
      export type OutputTuple = [recycler: string];
      export interface OutputObject {recycler: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardIssuedEvent {
      export type InputTuple = [submissionId: BigNumberish, user: AddressLike, reward: BigNumberish];
      export type OutputTuple = [submissionId: bigint, user: string, reward: bigint];
      export interface OutputObject {submissionId: bigint, user: string, reward: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionRejectedEvent {
      export type InputTuple = [submissionId: BigNumberish, recycler: AddressLike];
      export type OutputTuple = [submissionId: bigint, recycler: string];
      export interface OutputObject {submissionId: bigint, recycler: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SubmissionVerifiedEvent {
      export type InputTuple = [submissionId: BigNumberish, recycler: AddressLike];
      export type OutputTuple = [submissionId: bigint, recycler: string];
      export interface OutputObject {submissionId: bigint, recycler: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EWasteFi extends BaseContract {
    
    connect(runner?: ContractRunner | null): EWasteFi;
    waitForDeployment(): Promise<this>;

    interface: EWasteFiInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRecycler: TypedContractMethod<
      [recycler: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRewardBalance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getSubmission: TypedContractMethod<
      [submissionId: BigNumberish, ],
      [EWasteFi.SubmissionStructOutput],
      'view'
    >
    

    
    getSubmissionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getUserSubmissionIds: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    issueReward: TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recyclers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    rejectSubmission: TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeRecycler: TypedContractMethod<
      [recycler: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewardBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    submissionCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submissions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint, status: bigint, submittedAt: bigint, verifiedAt: bigint, rewardCredited: boolean }],
      'view'
    >
    

    
    submitEwaste: TypedContractMethod<
      [category: string, quantity: BigNumberish, weight: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    verifySubmission: TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRecycler'): TypedContractMethod<
      [recycler: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRewardBalance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSubmission'): TypedContractMethod<
      [submissionId: BigNumberish, ],
      [EWasteFi.SubmissionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSubmissionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserSubmissionIds'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'issueReward'): TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recyclers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rejectSubmission'): TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeRecycler'): TypedContractMethod<
      [recycler: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submissionCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submissions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, user: string, category: string, quantity: bigint, weight: bigint, reward: bigint, status: bigint, submittedAt: bigint, verifiedAt: bigint, rewardCredited: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'submitEwaste'): TypedContractMethod<
      [category: string, quantity: BigNumberish, weight: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifySubmission'): TypedContractMethod<
      [submissionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EWasteSubmitted'): TypedContractEvent<EWasteSubmittedEvent.InputTuple, EWasteSubmittedEvent.OutputTuple, EWasteSubmittedEvent.OutputObject>;
getEvent(key: 'RecyclerAdded'): TypedContractEvent<RecyclerAddedEvent.InputTuple, RecyclerAddedEvent.OutputTuple, RecyclerAddedEvent.OutputObject>;
getEvent(key: 'RecyclerRemoved'): TypedContractEvent<RecyclerRemovedEvent.InputTuple, RecyclerRemovedEvent.OutputTuple, RecyclerRemovedEvent.OutputObject>;
getEvent(key: 'RewardIssued'): TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
getEvent(key: 'SubmissionRejected'): TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
getEvent(key: 'SubmissionVerified'): TypedContractEvent<SubmissionVerifiedEvent.InputTuple, SubmissionVerifiedEvent.OutputTuple, SubmissionVerifiedEvent.OutputObject>;

    filters: {
      
      'EWasteSubmitted(uint256,address,string,uint256,uint256,uint256)': TypedContractEvent<EWasteSubmittedEvent.InputTuple, EWasteSubmittedEvent.OutputTuple, EWasteSubmittedEvent.OutputObject>;
      EWasteSubmitted: TypedContractEvent<EWasteSubmittedEvent.InputTuple, EWasteSubmittedEvent.OutputTuple, EWasteSubmittedEvent.OutputObject>;
    

      'RecyclerAdded(address)': TypedContractEvent<RecyclerAddedEvent.InputTuple, RecyclerAddedEvent.OutputTuple, RecyclerAddedEvent.OutputObject>;
      RecyclerAdded: TypedContractEvent<RecyclerAddedEvent.InputTuple, RecyclerAddedEvent.OutputTuple, RecyclerAddedEvent.OutputObject>;
    

      'RecyclerRemoved(address)': TypedContractEvent<RecyclerRemovedEvent.InputTuple, RecyclerRemovedEvent.OutputTuple, RecyclerRemovedEvent.OutputObject>;
      RecyclerRemoved: TypedContractEvent<RecyclerRemovedEvent.InputTuple, RecyclerRemovedEvent.OutputTuple, RecyclerRemovedEvent.OutputObject>;
    

      'RewardIssued(uint256,address,uint256)': TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
      RewardIssued: TypedContractEvent<RewardIssuedEvent.InputTuple, RewardIssuedEvent.OutputTuple, RewardIssuedEvent.OutputObject>;
    

      'SubmissionRejected(uint256,address)': TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
      SubmissionRejected: TypedContractEvent<SubmissionRejectedEvent.InputTuple, SubmissionRejectedEvent.OutputTuple, SubmissionRejectedEvent.OutputObject>;
    

      'SubmissionVerified(uint256,address)': TypedContractEvent<SubmissionVerifiedEvent.InputTuple, SubmissionVerifiedEvent.OutputTuple, SubmissionVerifiedEvent.OutputObject>;
      SubmissionVerified: TypedContractEvent<SubmissionVerifiedEvent.InputTuple, SubmissionVerifiedEvent.OutputTuple, SubmissionVerifiedEvent.OutputObject>;
    
    };
  }