/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface EWasteRewardVaultInterface extends Interface {
    getFunction(nameOrSignature: "creditReward" | "getRewardBalance" | "owner" | "registry" | "rewardBalances" | "setRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RegistryUpdated" | "RewardCredited"): EventFragment;

    encodeFunctionData(functionFragment: 'creditReward', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRewardBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRegistry', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'creditReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRewardBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRegistry', data: BytesLike): Result;
  }

  
    export namespace RegistryUpdatedEvent {
      export type InputTuple = [registry: AddressLike];
      export type OutputTuple = [registry: string];
      export interface OutputObject {registry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardCreditedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EWasteRewardVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): EWasteRewardVault;
    waitForDeployment(): Promise<this>;

    interface: EWasteRewardVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    creditReward: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getRewardBalance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rewardBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setRegistry: TypedContractMethod<
      [registryAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'creditReward'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRewardBalance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rewardBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setRegistry'): TypedContractMethod<
      [registryAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'RegistryUpdated'): TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;
getEvent(key: 'RewardCredited'): TypedContractEvent<RewardCreditedEvent.InputTuple, RewardCreditedEvent.OutputTuple, RewardCreditedEvent.OutputObject>;

    filters: {
      
      'RegistryUpdated(address)': TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;
      RegistryUpdated: TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;
    

      'RewardCredited(address,uint256)': TypedContractEvent<RewardCreditedEvent.InputTuple, RewardCreditedEvent.OutputTuple, RewardCreditedEvent.OutputObject>;
      RewardCredited: TypedContractEvent<RewardCreditedEvent.InputTuple, RewardCreditedEvent.OutputTuple, RewardCreditedEvent.OutputObject>;
    
    };
  }