/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'EWasteRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EWasteRegistry__factory>
getContractFactory(name: 'IRewardVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRewardVault__factory>
getContractFactory(name: 'EWasteRewardVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EWasteRewardVault__factory>

  getContractAt(name: 'EWasteRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EWasteRegistry>
getContractAt(name: 'IRewardVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRewardVault>
getContractAt(name: 'EWasteRewardVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EWasteRewardVault>

  deployContract(name: 'EWasteRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EWasteRegistry>
deployContract(name: 'IRewardVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardVault>
deployContract(name: 'EWasteRewardVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EWasteRewardVault>

  deployContract(name: 'EWasteRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EWasteRegistry>
deployContract(name: 'IRewardVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardVault>
deployContract(name: 'EWasteRewardVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EWasteRewardVault>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  