/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EWasteFi } from './EWasteFi.js';
export * as factories from './factories/index.js';
export { EWasteFi__factory } from './factories/EWasteFi__factory.js';