/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eWasteRegistrySol from './EWasteRegistry.sol/index.js';
export type { eWasteRegistrySol };
export type { EWasteRewardVault } from './EWasteRewardVault.js';
export * as factories from './factories/index.js';
export type { EWasteRegistry } from './EWasteRegistry.sol/EWasteRegistry.js';
export { EWasteRegistry__factory } from './factories/EWasteRegistry.sol/EWasteRegistry__factory.js';
export type { IRewardVault } from './EWasteRegistry.sol/IRewardVault.js';
export { IRewardVault__factory } from './factories/EWasteRegistry.sol/IRewardVault__factory.js';
export { EWasteRewardVault__factory } from './factories/EWasteRewardVault__factory.js';