/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EWasteRegistry__factory } from './EWasteRegistry__factory.js';
export { IRewardVault__factory } from './IRewardVault__factory.js';