/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRewardVault, IRewardVaultInterface } from "../../EWasteRegistry.sol/IRewardVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "creditReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRewardVault__factory {
    static readonly abi = _abi;
    static createInterface(): IRewardVaultInterface {
      return new Interface(_abi) as IRewardVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRewardVault {
      return new Contract(address, _abi, runner) as unknown as IRewardVault;
    }
  }
  