/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as eWasteRegistrySol from './EWasteRegistry.sol/index.js';
export { EWasteRewardVault__factory } from './EWasteRewardVault__factory.js';